### ISSUE TITLE
TypeError: jQuery.cookie is not a function

### ISSUE THREAD

**Issue by pcolmant** [mbraak/django-mptt-admin#125]
Marco,

The 0.3.4 version requires jQuery.cookie but doesn't include it.

Edge : SCRIPT438: Object doesn't support property or method 'cookie'
django_mptt_admin.js (1,970)
Firefox : TypeError: jQuery.cookie is not a function
django_mptt_admin.js:1:976

The 0.3.3 version works perfectly.

Kr
Patrick

**Comment by mbraak** [comment]
Hello Patrick,

I cannot reproduce this error in the example project. I tried it on Chome and Firefox.

Note that the `jQuery.cookie` library is included in the `django_mptt_admin.js` file. It is loaded using browserify.

I cannot explain why it does not work in your situation. Another user had a similar problem that was caused by loading extra jquery plugins.

Greetings,
Marco

**Comment by pcolmant** [comment]
Hello Marco,

Same error with Chrome.
To solve it, I made a raw copy/paste of the content of
jquery-cookie/jquery.cookie.js taken from django_mptt_admin==0.3.3 at the
end of jquery_namespace.js from django_mptt_admin==0.3.4.

After clearing my browser(s) cache  it works perfectly with this
"customized" jquery_namespace.js.

Lots of thanks for django_mptt_admin which is very usefull.

Patrick

Le dim. 27 mars 2016 à 22:31, Marco Braak <notifications@github.com> a
écrit :

**Comment by mbraak** [comment]
Great that it works! Although I still don't understand why I cannot reproduce this error.

**Comment by mbraak** [comment]
I can now reproduce the error. This is fixed in the master branch.

**Comment by mbraak** [comment]
Fixed in new version 0.3.6
